dist: trusty

sudo: required

install:
  - sudo apt-get -y install snapd
  - sudo snap install hugo

script: /snap/bin/hugo 

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
  