before_install:
  - sudo apt-get update

install:
  - sudo pip install Pygments
  - sudo apt-get install -y hugo

script: hugo

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
  